#!/bin/bash

set -eu # -x for verbose logging to juju debug-log

umask 002

app_name=`config-get app_name`
app_user=`config-get app_user`
app_repo=`config-get app_repo`
app_port=`config-get app_port`

update_get_app() {
  juju-log "Updating/Installing ${app_name}..."
  export GOPATH=/home/${app_user}/go
  go get -u ${app_repo}
}

update_init() {
  cat > /etc/init/${app_name}.conf <<EOS
description "${app_name} go web server"
 
start on (net-device-up
          and local-filesystems
          and runlevel [2345])
stop on runlevel [!2345]
 
expect fork
respawn
 
script
  export PORT=${app_port}
  exec /home/${app_user}/go/bin/$(basename ${app_repo}) &
end script
EOS
}

update_get_app
update_init

juju-log "restarting app ${app_name}..."
service ${app_name} restart || service ${app_name} start