#!/bin/bash

set -eu # -x for verbose logging to juju debug-log

umask 002

app_name=`config-get app_name`
app_user=`config-get app_user`
app_repo=`config-get app_repo`
app_port=`config-get app_port`

apt-get -y install -qq git-core

install_go() {
  juju-log "Installing go..."
  apt-get update
  apt-get -y install -qq golang
  mkdir -p /home/${app_user}/go
}
[[ -x /usr/bin/go ]] || install_go
