#!/bin/bash

set -eu # -x for verbose logging to juju debug-log

umask 002

app_name=`config-get app_name`
app_user=`config-get app_user`
app_repo=`config-get app_repo`
app_port=`config-get app_port`

apt-get -y install -qq git-core

install_go() {
  juju-log "Installing go..."
  apt-get update
  apt-get -y install -qq golang
}
[[ -x /usr/bin/go ]] || install_go

install_app() {
  juju-log "Installing ${app_name}..."
  mkdir -p /home/${app_user}/go
  export GOROOT=/home/${app_user}/go
  export PATH=$PATH:$GOROOT/bin
  go get ${app_repo}
  cat > /etc/init/${app_name}.conf <<EOS
description "${app_name} go web server"
 
start on (net-device-up
          and local-filesystems
          and runlevel [2345])
stop on runlevel [!2345]
 
expect fork
respawn
 
script
  export PORT=${app_port}
  exec /usr/bin/node ${app_dir}/server.js &
end script
EOS
}
[[ -d /home/${app_user}/go/${app_repo} ]] || install_app
